### ISSUE TITLE
Can redirect URIs be made static?

### ISSUE THREAD

**Issue by cooperthompson** [siteadmin/inferno#67]
Currently, it appears that the redirect URI used by Inferno is dynamic, with what looks like a session or test ID or something in the URL:

http://inferno.healthit.gov/inferno/9OQgz2pxcQt/2BxrGc/redirect

For systems that perform strict validation of redirect URIs, a new redirect would need to be registered by the owner of the client for each new set of tests run.

If instead, a fixed redirect URI were used, where the session/test identifier is passed as the state parameter, that would allow a single client registration to be used.

**Comment by jmandel** [comment]
(in theory this should work out fine by using a static redirect endpoint, and mapping the OAuth state back to the session id within the app)

**Comment by arscan** [comment]
I hadn't considered using state as the mechanism to allow for static redirect endpoints, that seems like a pretty elegant solution that should always work and is trivial to implement.

However, it was intentional to not allow a single client registration to be used across these 'test instances'.  We are considering registration as something that needs to get tested itself, and isn't part of the setup as Inferno.  I suppose I think of Inferno more of an app factory than an app, where each app it creates starts from a completely blank slate and has to do everything (including a new registration).  By generating new endpoints we are requiring the server to prove that they can register a new app each time.  Does that make sense?

I'm not sure if this is more of a pain than it is worth though.  Registration is tedious on some implementations, so from a practical perspective perhaps 1 registration is enough (and the user just can save and reuse client_ids across test instances).

**Comment by jmandel** [comment]
That's an interesting perspective. I think you can still apply the "app factory" model even if the redirect happens outside of any of the specific factory-produced "apps". In other words, if you take the suggestion here, you can still think of Inferno as an app factory with isolated apps; it's just that in some subsets of these isolated apps, a dev might choose to reuse a client id -- which is a pretty minimal kind of cross-over, and it only happens if devs choose it.

**Comment by arscan** [comment]
After thinking a little more about it, I agree.  Presumably somebody at some point registered an app by virtue of a client_id being available, so why have the user 'prove' it again if it is tedious and they have a client_id ready to go?  

@radamson  and I spoke a bit about this a few weeks back and were thinking of supporting both the dynamic and static options.  But I only see upsides to just moving to static and using the session info to track which instance to point the user back to.

**Comment by cooperthompson** [comment]
Just checking in on whether static URLs might be an enhancement with an near-term ETA - or whether it's a more nebulous/future thing?

We definitely have interest in using inferno for testing, but can't practically use it until it supports static redirect URIs.

**Comment by radamson** [comment]
Stay tuned...@arscan worked on this and it should be available in the next release @cooperthompson

**Comment by arscan** [comment]
We updated Inferno to support this by using `state` as a unique key that allows Inferno to reassociate the user with a running test sequence.  Thanks for the suggestion!  So now the redirect URI on inferno.healthit.gov is `https://inferno.healthit.gov/inferno/oauth2/static/launch`

Since we rely on `state`, if the server doesn't pass it back properly, then instead of a 'pretty' Inferno test failure in the test interface, the test user gets stuck. We may consider storing this information in a cookie as well to make the user experience more seemless.

**Comment by cooperthompson** [comment]
Looks great.  I was able to test with an Inferno client I registered on open.epic.com: 7b6416f9-3a5d-4d70-92ac-92b6ec7c1c98.

We don't have well-known stuff implemented, but we can pass Standalone launch now.  

Thanks!
